# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: PackerBuild@1
  inputs:
    templateType: 'builtin'
    ConnectedServiceName: 'Azure subscription 1(1)(7c4ca187-f32c-4894-b2b8-f35fe76aa5f1)'
    isManagedImage: false
    location: 'westeurope'
    storageAccountName: 'eschoolstorage'
    azureResourceGroup: 'VM'
    baseImageSource: 'default'
    baseImage: 'Canonical:UbuntuServer:18.04-LTS:linux'
    packagePath: '$(System.DefaultWorkingDirectory)/_IvanSavchyn194.eSchool/drop/target/eschool.jar'
    deployScriptPath: 'deploy.sh'
    imageUri: 'vmss-test'
- task: AzureVmssDeployment@0
  inputs:
    azureSubscription: 'Azure subscription 1(1)(7c4ca187-f32c-4894-b2b8-f35fe76aa5f1)'
    action: 'Update image'
    vmssName: 'vmss-eschool-sav'
    vmssOsType: 'Linux'
    imageUrl: 'vmss-test'
    skipArchivingCustomScripts: true