# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop

pool:
  vmImage: ubuntu-18.04

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package -Dmaven.test.skip=true'
- task: AzureCLI@1
  inputs:
    azureSubscription: 'Azure-Devops'
    scriptLocation: 'inlineScript'
    inlineScript: |
       az storage blob upload -c eschool -f $(system.defaultworkingdirectory)/**/eschool.jar
           --account-name eschoolstorage \
           --connection-string DefaultEndpointsProtocol=https;AccountName=eschoolstorage;AccountKey=B+Nkz7OdNAOIoCGKtye/2A8JwYeqdG2A6GTY6wXWEQcq0phn173F+lCAIohmfSwBtdR7gRBqA9yo34cPlxxzTQ==;EndpointSuffix=core.windows.net \
           --account-key B+Nkz7OdNAOIoCGKtye/2A8JwYeqdG2A6GTY6wXWEQcq0phn173F+lCAIohmfSwBtdR7gRBqA9yo34cPlxxzTQ== \
- task: AzureCLI@1
  inputs:
    azureSubscription: 'Azure-Devops'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az vmss extension set \
          --publisher Microsoft.Azure.Extensions \
          --version 2.0 \
          --name CustomScript \
          --resource-group VM \
          --vmss-name eschool-vmss-test \
          --settings '{ "fileUris": ["https://eschoolstorage.blob.core.windows.net/eschool/update.sh"], "commandToExecute": "./update.sh" }'